### PR TITLE
added addEnergyIQMeterReading

### PR DESCRIPTION
**Pull request by ViTra86**

### CODE REVIEW

**Comment by slcp** [comment]
Hey :) the changes in this PR should likely have some tests supporting them in keeping with the rest of the code in this project.

**Comment by mattdavis90** [comment]
Hi @ViTra86 , Thanks for the PR and the added functionality. I'm happy to merge this. Do you use the library as part of NodeRed? Would you like this call adding in to the wrapper library?

**Comment by mattdavis90** [comment]
This is now in the v0.13.2 release

**Comment by ViTra86** [comment]
Great thanks! 

Yes I do use it in NodeRed and would like to make the call from there. If we can make it available there that would be great.

**Pull request merged**
