### PR TITLE
api(setZoneOverlays): allow boost heating requests

### PR DESCRIPTION
**Pull request by abn**

### CODE REVIEW

**Comment by mattdavis90** [comment]
Is this part of the Tado API? I haven't seen that field before. They previously just put the temperature up to 25C for an hour and cycled through every zone.

**Comment by abn** [comment]
Yeah; I was just reversing their web-api call when hitting the boost button. Seems they now have the `isBoost` property in there. It does seem to also impact the zone state as a side-effect, but I have not got that far yet.

**Comment by mattdavis90** [comment]
Ok, cool. Want me to hold off merging while you continue looking into it, or do you think this is complete enough?

**Comment by abn** [comment]
This should be complete enough. I have verified just now that the data in the zone state has no impact.

**Pull request merged**
