### PR TITLE
ci: add initial dependabot configuration

### PR DESCRIPTION
**Pull request by abn**
Proposing a dependabot config to automate dependency bump chores. Feel free to close if not necessary.

### CODE REVIEW

**Comment by mattdavis90** [comment]
Seems reasonable. Thanks

**Comment by abn** [comment]
Ah too quick :) Sorry marked the PR as Draft because there was an issue with the config. Will send another PR with fix.

**Comment by mattdavis90** [comment]
That's ok - I noticed the issue on merge. I couldn't see it on my phone so merged ;)

**Comment by abn** [comment]
All good, fixed config is at #66.

**Pull request merged**
